// <auto-generated />
namespace MvcTempates.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SomeFirstChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SomeFirstChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201212202102351_SomeFirstChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
